#!/bin/bash

source "./inc/load_dotenv.sh"
source "./inc/utils.sh"
source "./inc/help.sh"

CONTAINER_NAME='swag'

case "$1" in
  'create')
    docker create \
    --name=$CONTAINER_NAME \
    --cap-add=NET_ADMIN \
    -e PUID=$PUID \
    -e PGID=$PGID \
    -e TZ=$TZ \
    -e URL=$URL \
    -e SUBDOMAINS=www, \
    -e VALIDATION=http \
    -e STAGING=false \
    -p 443:443 \
    -p 80:80 \
    -v ./config:/config \
    --restart unless-stopped \
    ghcr.io/linuxserver/swag
  ;;
  'remove')
    docker container rm $CONTAINER_NAME
  ;;
  br
  *)
    base_help
  ;;
esac

